version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rykosystem
      POSTGRES_PASSWORD: rykosystem_password
    ports:
      - "5432:5432"

  web:
    depends_on:
      - db
    build: .
    container_name: rykosystem
    ports:
    - "5000:5000"
