version: '2'

services:
  web:
    volumes:
      - .:/app
    environment:
      PORT: 5000
      PYTHONUNBUFFERED: 1
      DEBUG_MODE: ${DEBUG_MODE}
      GOOGLE_DRIVE_AUTH: ${GOOGLE_DRIVE_AUTH}

  worker:
    environment:
      DEBUG_MODE: ${DEBUG_MODE}
      PYTHONUNBUFFERED: 1
      GOOGLE_DRIVE_AUTH: ${GOOGLE_DRIVE_AUTH}
