version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rykosystem
      POSTGRES_PASSWORD: rykosystem_password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    image: rykosystem
    container_name: rykosystem
    depends_on:
      - db
      - redis
    ports:
    - "5000:5000"
    volumes:
      - .:/app

  worker:
    image: rykosystem
    command: python worker.py
    depends_on:
      - redis
    volumes:
      - .:/app
