# fly.toml app configuration file generated for programforschools-backend-restless-lake-617 on 2024-08-31T13:36:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'programforschools-backend-restless-lake-617'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
