version: 2.1

orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.13
        environment:
          DEBUG_MODE: 1
          GOOGLE_DRIVE_AUTH: ${GOOGLE_DRIVE_AUTH}
      - image: cimg/postgres:15.1
        environment:
          POSTGRES_USER: rykosystem_test
          POSTGRES_DB: rykosystem_test
          POSTGRES_PASSWORD: rykosystem_password_test
          POSTGRES_HOST: localhost
      - image:  cimg/redis:6.2.6
    steps:
      - checkout
      - run: 
          name: Checkout postesql connection, display tables 
          environment: 
            DATABASE_URL: postgres://rykosystem_test:rykosystem_password_test@localhost/rykosystem_test
          command: psql -d ${DATABASE_URL} -c "\dt"
                   
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install pytest-html
          command: pip install --user pytest-html
      - run:
          name: Run unit tests
          command: cd tests | 
                   pytest --junitxml=test-results/junit.xml --html=test-results/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build-workflow:
    jobs:
      - build-and-test
